
# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html
[workspace]
members = [ "examples/ch_01/sha1_cracker", "examples/ch_01/smart_pointers","examples/ch_01/snippets/enums"]

exclude = []

# new crates created should not create their own .git
[cargo-new]
vcs = "none"

# This prevents a Travis CI error when building for Windows.
resolver = "2"

[workspace.package]
version = "0.0.0"
authors = ["pgdev"]
repository = "https://github.com/paulgsc/black_hat_rust"
homepage = "https://maishatu.com/"
license = "MIT"
edition = "2021"

[workspace.dependencies]
