[package]
name = "sha1_cracker"
version.workspace = true
authors.workspace = true
repository.workspace = true
homepage.workspace = true
license.workspace = true
edition.workspace = true

[dependencies]
sha-1 = "0.9"
hex = "0.4"